[workspace]
members = ["crates/mediapulse-core", "src-tauri"]
resolver = "3"

[workspace.package]
authors = ["useless-rs"]
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/useless-rs/MediaPulse"
rust-version = "1.85"
version = "0.1.1"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
